from algorithms.RepeatedDNASequences import *
from dataStructures import *

print(Solution().findRepeatedDnaSequences("ACCCTCCCACTTGGATGCCGCACGTGTCGACTAACCTTACATTGTCCCCCCACCTCCAGACGGTTAACTCTTGAAATGGGGGAATAGCTGCTTGCGCGTG"))